name = "uix-playground-backend"
main = "src/worker.js"
compatibility_date = "2023-08-14"
node_compat = true
usage_model = "unbound"

 [[d1_databases]]
 binding = "DB"
 database_name = "UIXP"
 database_id = "{id}"

[[kv_namespaces]]
binding = "UIXP"
id = "{id}"
preview_id = "{id}"